// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTag'](arg1, arg2, arg3);
}

export function CheckMissingGames() {
  return window['go']['main']['App']['CheckMissingGames']();
}

export function CreateTag(arg1, arg2) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function DeleteGames(arg1) {
  return window['go']['main']['App']['DeleteGames'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ImportGames(arg1) {
  return window['go']['main']['App']['ImportGames'](arg1);
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function ListGames() {
  return window['go']['main']['App']['ListGames']();
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function OpenGameFolder(arg1) {
  return window['go']['main']['App']['OpenGameFolder'](arg1);
}

export function RelinkGame(arg1) {
  return window['go']['main']['App']['RelinkGame'](arg1);
}

export function RemoveTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveTag'](arg1, arg2);
}

export function RenameGame(arg1, arg2) {
  return window['go']['main']['App']['RenameGame'](arg1, arg2);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function ResetCover(arg1) {
  return window['go']['main']['App']['ResetCover'](arg1);
}

export function ResetLibrary() {
  return window['go']['main']['App']['ResetLibrary']();
}

export function ScanFolders(arg1) {
  return window['go']['main']['App']['ScanFolders'](arg1);
}

export function SelectAndScanFolder() {
  return window['go']['main']['App']['SelectAndScanFolder']();
}

export function SelectCoverImage(arg1) {
  return window['go']['main']['App']['SelectCoverImage'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetFavorite'](arg1, arg2);
}

export function SetTagAxis(arg1, arg2) {
  return window['go']['main']['App']['SetTagAxis'](arg1, arg2);
}

export function SetTagColor(arg1, arg2) {
  return window['go']['main']['App']['SetTagColor'](arg1, arg2);
}

export function SetTool(arg1, arg2) {
  return window['go']['main']['App']['SetTool'](arg1, arg2);
}
