// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {health} from '../models';
import {main} from '../models';
import {scan} from '../models';

export function AddTag(arg1:number,arg2:string,arg3:string):Promise<store.Tag>;

export function CheckMissingGames():Promise<Array<health.Result>>;

export function CreateTag(arg1:string,arg2:string):Promise<store.Tag>;

export function DeleteGame(arg1:number):Promise<void>;

export function DeleteGames(arg1:Array<number>):Promise<main.DeleteResult>;

export function DeleteTag(arg1:number):Promise<void>;

export function ImportGames(arg1:Array<scan.Detected>):Promise<main.ImportResult>;

export function LaunchGame(arg1:number):Promise<void>;

export function ListGames():Promise<Array<store.Game>>;

export function ListTags():Promise<Array<store.TagWithCount>>;

export function OpenGameFolder(arg1:number):Promise<void>;

export function RelinkGame(arg1:number):Promise<store.Game>;

export function RemoveTag(arg1:number,arg2:number):Promise<void>;

export function RenameGame(arg1:number,arg2:string):Promise<void>;

export function RenameTag(arg1:number,arg2:string):Promise<void>;

export function ResetCover(arg1:number):Promise<void>;

export function ResetLibrary():Promise<void>;

export function ScanFolders(arg1:Array<string>):Promise<Array<scan.Detected>>;

export function SelectAndScanFolder():Promise<Array<scan.Detected>>;

export function SelectCoverImage(arg1:number):Promise<string>;

export function SetFavorite(arg1:number,arg2:boolean):Promise<void>;

export function SetTagAxis(arg1:number,arg2:string):Promise<void>;

export function SetTagColor(arg1:number,arg2:string):Promise<void>;

export function SetTool(arg1:number,arg2:string):Promise<void>;
